In [1]:
import numpy as np


In [13]:
arr = np.array([[1,2],[3,4],[5,6]])


In [3]:
arr


array([1, 2, 3])

In [9]:
arr + arr

array([[2, 4],
       [6, 8]])

In [11]:
arr

array([[1, 2],
       [3, 4]])

In [14]:
arr.shape

(3, 2)

In [18]:
    arr[:,0] #all first cells second dim

array([1, 3, 5])

In [19]:
arr1 = np.array([1,2,3,4,5,6])

In [25]:
arr[1:,1:]


array([[4],
       [6]])

In [33]:
np.repeat(3,10)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [32]:
np.max(8)

8

In [34]:
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [35]:
arr2 = np.array([[10,20],[30,40],[50,60]])

In [36]:
arr * arr2

array([[ 10,  40],
       [ 90, 160],
       [250, 360]])

In [37]:
%timeit arr * arr2 #visa tidsåtgång (grej i jupyter)

537 ns ± 11.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [42]:
def my_decorator(func): #all func could be uaed s decorators -returns new func
   def func_wrapper(*args, **kwargs):
       return "<p>{0}</p>".format(func(*args, **kwargs))
   return func_wrapper

class Person(object):
    def __init__(self):
        self.name = "John"
        self.family = "Doe"

    @my_decorator
    #following becomes input arg to my decorator
    def get_fullname(self):
        return self.name+" "+self.family

my_person = Person()

print(my_person.get_fullname())



<p>John Doe</p>
